### PR TITLE
AboutItems generation using linq

### PR DESCRIPTION
**Pull request by ch1seL**

### CODE REVIEW

**Comment by RemiBou** [comment]
Thanks, but f I understand well your code, you miss the point, it needs to create a new Toss after every blank line, not for every line. (I should unit test this)

**Comment by ch1seL** [comment]
> Thanks, but f I understand well your code, you miss the point, it needs to create a new Toss after every blank line, not for every line. (I should unit test this)

I just use a double newline as a Tosses separator. I checked it and the content matches your version.

**Comment by RemiBou** [comment]
Right ! Perfect thanks

**Comment by RemiBou** [comment]
merged :)

**Pull request merged**
